title: Perian Development
baseurl: ""
url: https://periandevelopment.github.io

privacymail: "periandevelopment+privacy@gmail.com"
legalmail: "periandevelopment+legal@gmail.com"
contactmail: "periandevelopment+contact@gmail.com"
businessmail: "periandevelopment+business@gmail.com"
supportmail: "periandevelopment+support@gmail.com"
feedbackmail: "periandevelopment+feedback@gmail.com"